/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.komododev.money_management;

import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author https://github.com/trbp-lost
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        TableBalance();
        
        // Display pie chart in jPanel2
        PieChart(pieChartAnnual, 80, 20, "Annual Chart");
        PieChart(pieChartMonthly, 50, 50, "Montly Chart");
        
        buttonModify.setVisible(false);
        buttonCancel.setVisible(false);
        dropDownTypeBalance.setSelectedItem(dropDownTypeBalance.getItemAt(2));
    }
    

    private Connection conn = Database.Connect();
    
    private void ClearInput(){
        dropDownTypeBalance.setSelectedItem(dropDownTypeBalance.getItemAt(2));
        textBalance.setText("");
        textInformation.setText("");
    }
    
    private void TableBalance(){
        DefaultTableModel dft = (DefaultTableModel)tableBalance.getModel();
        Database.ShowTable(conn, dft);
    }
    
    private boolean Validation(String balance, Object selectedBalanceType){
        
        if (selectedBalanceType.equals(dropDownTypeBalance.getItemAt(2))){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Type Balance incorrect", "An error has occurred.", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if (balance.equals("") || balance.equals("0") || !balance.matches("\\d+")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Balance incorrect", "An error has occurred.", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void PieChart(javax.swing.JPanel panel, int deposit, int withdraw, String name) {
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("Deposit - " + deposit + "%", deposit);
        pieDataset.setValue("Withdraw - " + withdraw + "%", withdraw);

        // Create the pie chart
        JFreeChart chart = ChartFactory.createPieChart(
            name,              // chart title
            pieDataset,        // data
            true,              // include legend
            true,
            false
        );

        // Customize the plot
        PiePlot plot = (PiePlot)chart.getPlot();
        plot.setForegroundAlpha(0.6f); // Set transparency for 2D plot

        // Add the chart to a ChartPanel
        ChartPanel chartPanelContainer = new ChartPanel(chart);
        chartPanelContainer.setPreferredSize(panel.getSize());

        panel.removeAll();
        panel.setLayout(new java.awt.BorderLayout()); 
        panel.add(chartPanelContainer, java.awt.BorderLayout.CENTER);
        panel.validate(); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonSubmit = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textBalance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textInformation = new javax.swing.JTextArea();
        buttonModify = new javax.swing.JButton();
        dropDownTypeBalance = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        pieChartAnnual = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        pieChartMonthly = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<>();
        buttonDelete = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBalance = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(987, 235, 81, -1));

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 235, 81, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Welcome, User!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        textBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(textBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(808, 91, 428, -1));

        jLabel2.setText("Balance :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 94, -1, -1));

        jLabel3.setText("Information :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 131, -1, -1));

        textInformation.setColumns(20);
        textInformation.setRows(5);
        jScrollPane3.setViewportView(textInformation);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(808, 131, 428, -1));

        buttonModify.setText("Modify");
        buttonModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyActionPerformed(evt);
            }
        });
        jPanel1.add(buttonModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(808, 235, 81, -1));

        dropDownTypeBalance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposit", "Withdraw", " " }));
        dropDownTypeBalance.setFocusCycleRoot(true);
        dropDownTypeBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownTypeBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(dropDownTypeBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(808, 51, 428, -1));

        jLabel4.setText("Type :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 54, -1, -1));

        pieChartAnnual.setBackground(new java.awt.Color(0, 255, 255));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("pie chart total pada \nkeseluruhan");
        jScrollPane5.setViewportView(jTextArea2);

        javax.swing.GroupLayout pieChartAnnualLayout = new javax.swing.GroupLayout(pieChartAnnual);
        pieChartAnnual.setLayout(pieChartAnnualLayout);
        pieChartAnnualLayout.setHorizontalGroup(
            pieChartAnnualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pieChartAnnualLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pieChartAnnualLayout.setVerticalGroup(
            pieChartAnnualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pieChartAnnualLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jPanel1.add(pieChartAnnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 58, -1, -1));

        pieChartMonthly.setBackground(new java.awt.Color(255, 51, 255));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("pie chart total \npada bulan ini");
        jScrollPane6.setViewportView(jTextArea4);

        javax.swing.GroupLayout pieChartMonthlyLayout = new javax.swing.GroupLayout(pieChartMonthly);
        pieChartMonthly.setLayout(pieChartMonthlyLayout);
        pieChartMonthlyLayout.setHorizontalGroup(
            pieChartMonthlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pieChartMonthlyLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pieChartMonthlyLayout.setVerticalGroup(
            pieChartMonthlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pieChartMonthlyLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jPanel1.add(pieChartMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 58, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        tableBalance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Date", "Deposit", "Withdraw", "Balance", "Information", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBalance.getTableHeader().setReorderingAllowed(false);
        tableBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBalanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBalance);
        if (tableBalance.getColumnModel().getColumnCount() > 0) {
            tableBalance.getColumnModel().getColumn(6).setMinWidth(0);
            tableBalance.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonDelete)
                        .addGap(995, 995, 995)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buttonDelete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dft = (DefaultTableModel)tableBalance.getModel();
        int selectedIndex = tableBalance.getSelectedRow();

        if (Database.Delete(conn, selectedIndex, dft)) {
            Toolkit.getDefaultToolkit().beep();
            ClearInput();
            TableBalance();

            buttonModify.setVisible(false);
            buttonCancel.setVisible(false);
            buttonSubmit.setVisible(true);

        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Not Avalaible", "Failed Input.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void dropDownTypeBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownTypeBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropDownTypeBalanceActionPerformed

    private void buttonModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyActionPerformed
        // TODO add your handling code here:
        String balance, information, typeBalance;

        typeBalance = (String) dropDownTypeBalance.getSelectedItem();
        balance = textBalance.getText();
        information = textInformation.getText();

        Object selectedBalanceType = dropDownTypeBalance.getSelectedItem();
        DefaultTableModel dft = (DefaultTableModel)tableBalance.getModel();
        int selectedIndex = tableBalance.getSelectedRow();

        if (!Validation(balance, selectedBalanceType)){
            return;
        }

        if (Database.Modify(conn, selectedIndex, dft, balance, information, typeBalance)) {
            Toolkit.getDefaultToolkit().beep();
            ClearInput();
            TableBalance();

        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Please put Number", "Failed Input.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonModifyActionPerformed

    private void textBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBalanceActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        ClearInput();

        buttonModify.setVisible(false);
        buttonCancel.setVisible(false);
        buttonSubmit.setVisible(true);
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:
        String balance, information, typeBalance;

        typeBalance = (String) dropDownTypeBalance.getSelectedItem();
        balance = textBalance.getText();
        information = textInformation.getText();

        Object selectedBalanceType = dropDownTypeBalance.getSelectedItem();

        if (!Validation(balance, selectedBalanceType)){
            return;
        }

        if (Database.Insert(conn, balance, information, typeBalance)) {
            Toolkit.getDefaultToolkit().beep();
            ClearInput();
            TableBalance();

        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Please put Number", "Failed Input.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void tableBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBalanceMouseClicked
        // TODO add your handling code here:
        buttonModify.setVisible(true);
        buttonCancel.setVisible(true);
        buttonSubmit.setVisible(false);

        DefaultTableModel dft = (DefaultTableModel)tableBalance.getModel();
        int selectedIndex = tableBalance.getSelectedRow();
        double depositBalance = Double.parseDouble(dft.getValueAt(selectedIndex, 2).toString());

        if (depositBalance > 0) {
            dropDownTypeBalance.setSelectedItem(dropDownTypeBalance.getItemAt(0));
            textBalance.setText(dft.getValueAt(selectedIndex, 2).toString());
        }
        else {
            dropDownTypeBalance.setSelectedItem(dropDownTypeBalance.getItemAt(1));
            textBalance.setText(dft.getValueAt(selectedIndex, 3).toString());
        }

        textInformation.setText(dft.getValueAt(selectedIndex, 5).toString());
    }//GEN-LAST:event_tableBalanceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Dashboard().setVisible(true);
//            }
//        });
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonModify;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JComboBox<String> dropDownTypeBalance;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JPanel pieChartAnnual;
    private javax.swing.JPanel pieChartMonthly;
    private javax.swing.JTable tableBalance;
    private javax.swing.JTextField textBalance;
    private javax.swing.JTextArea textInformation;
    // End of variables declaration//GEN-END:variables
}
